### ISSUE TITLE
dateview setup

### ISSUE THREAD

**Issue by alejandrorbradford** [Tuslareb/JBDatePicker#11]
![screen shot 2017-01-30 at 10 44 24 am](https://cloud.githubusercontent.com/assets/14142837/22429601/1e234742-e6d9-11e6-9b0f-e4303ad79861.png)

I'm not able to see day's numbers, just the day names on top. Am I missing something?

Thanks,

**Comment by Tuslareb** [comment]
I'm not sure what's happening here. You have set the delegate, otherwise you wouldn't see the weekday labels. What's the gray background and how did you set it? Can you give me some more details about your setup?

**Comment by alejandrorbradford** [comment]
yeah, delegate is OK now, the gray view is the whole JBDatePickerView object. Tried in code and on storyboard, getting the same results, not able to see the days.

**Comment by alejandrorbradford** [comment]
there is a uilabel behind the datepickerview, looks like it's only loading the top view
![screen shot 2017-01-30 at 11 44 20 am](https://cloud.githubusercontent.com/assets/14142837/22432052/a9ac8398-e6e1-11e6-9139-4e03ab450458.png)

**Comment by alejandrorbradford** [comment]
datePicker.presentedMonthView?.monthDescription . ----- returning correct month here tho

**Comment by Tuslareb** [comment]
Can you please check the version of JBDatePicker you installed? It should be 1.1.2.

**Comment by Tuslareb** [comment]
I can't reproduce the issue without more info about your specific setup. I just tried a new testproject and it just works fine. The only thing I can come up with right now is that you have installed an old version of JBDatePicker. The way it draws it subviews was changed recently. Please run pod update and check if 1.1.2 is installed.
