### ISSUE TITLE
Add more custom features?

### ISSUE THREAD

**Issue by lynnleelhl** [Tuslareb/JBDatePicker#12]
I recently found your project and it is really fancy, besides I like Swift anyway. 

I'd like to use it in my project but there's still something I want to customize, such as the scroll direction, I might prefer to change to vertical, or the size of the date cell; what's more, I might want to pick a range of dates, e.g. I pick a start date, say Feb. 3rd, and an end date, maybe Feb. 5th, that means I picked 3rd, 4th, and 5th. 

So I just wonder if there's any chance you add these custom features?  Or if you need, I can contribute. :)

**Comment by Tuslareb** [comment]
Hi and thank you. I'm glad you like it. 

To answer your questions: 

* Selecting multiple dates (range selection) is definitely on the roadmap. I try to get into this as soon as possible. I have some clear ideas about how I want to do this.

* Vertical scrolling could be a nice feature to integrate. Feel feel to contribute!

**Comment by joaopedrok** [comment]
You can add in delegate to add custom UIFont for the days and days of the week.

**Comment by Tuslareb** [comment]
@joaopedrok Yes, this is on my todo list.

**Comment by Tuslareb** [comment]
@joaopedrok version 1.2.0 brings support for custom fonts. Available now.

**Comment by joaopedrok** [comment]
@Tuslareb thanks. I needed and i downloaded the code and change it for me. But nice! Congratulations for the component.
