### ISSUE TITLE
Year View

### ISSUE THREAD

**Issue by rlee1990** [Tuslareb/JBDatePicker#13]
Hi is there any way to get a option like next month and previous month for years? Sorry still learning swift 3.

**Comment by Tuslareb** [comment]
I'm not sure I fully understand what you mean to ask. Can you please try to explain what you would like to do?

**Comment by rlee1990** [comment]
Just asking if there are any options to skip by year the way we can with months?

**Comment by Tuslareb** [comment]
Ok, now I get it. That's not possible at the moment, but it should be easy to create. I'll put it on my todo list.

**Comment by rlee1990** [comment]
Thanks
