### ISSUE TITLE
Multiple PreSelect Date

### ISSUE THREAD

**Issue by rupeshh2123** [Tuslareb/JBDatePicker#14]
Hi, I just wanted to know if we could preselect multiple dates in a particular month.

**Comment by Tuslareb** [comment]
No, not at this moment. This is on the roadmap however.

**Comment by raghuphonegap1** [comment]
Hi , i need to preselect the date in particular month . Please help me out on this.

**Comment by Tuslareb** [comment]
Just return the Date object you want on the dateToShow variable. See the example project. 

`var dateToShow: Date { return a Date object}`

**Comment by raghuphonegap1** [comment]
Thanks tuslareb,
But i need to preselect the multiple dates in multiple months . Please help me out on this.

**Comment by Tuslareb** [comment]
This is not possible at the moment. I will certainly look into this for a future release, but please don't wait for it as I'm busy with some other projects at the moment. Feel free to contribute however.

**Comment by jordanhbuiltbyhq** [comment]
I have a need to preselect multiple dates as well, +1

**Comment by gyanaprakash** [comment]
How can i show dot in some particular date. can you guide me. thanks
