### ISSUE TITLE
Option to show dates (in month) before today

### ISSUE THREAD

**Issue by QuocLoi** [Tuslareb/JBDatePicker#18]
Hi, thanks for your nice library.

I am using JBDatePicker and I want to show the past days (dates before today) in other colour and I don't want to let user interact with these dates. Is there any way I can do that? I don't see any options about the past dates in you code.

Thanks

**Comment by Tuslareb** [comment]
No, not at the moment. I'll put this on my feature request list. I could make an option to disable the past dates and make another option to give these dates another color. However, this could lead to strange looking calendars because the next and previous month dates also have another color.

**Comment by Tuslareb** [comment]
Update: thanks to @garethknowles your wished came true. See the updated readme.
