### ISSUE TITLE
Add indicator

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [Tuslareb/JBDatePicker#21]
Hi Tuslareb,

Your project is great! It helps me allot. But can i ask how to add indicator for each day? Please refer to the images.. I hope its possible.. Thanks More Powers! 
![screen shot 2017-04-25 at 10 35 52 am](https://cloud.githubusercontent.com/assets/17594695/25366549/01b967a0-29a3-11e7-93dd-4487ef1770c9.png)

**Comment by Tuslareb** [comment]
Thank you! An indicator is not possible at the moment. I'll take this into consideration for a future release.

**Comment by nicoaureliovillanueva** [comment]
INA KA! Translation = Thank You!

**Comment by gyanaprakash** [comment]
How can i show dot in some particular date. can you guide me. thanks

**Comment by Tuslareb** [comment]
You mean like an indicator dot? That is not possible at the moment.
