### ISSUE TITLE
Customise/Disable certain days in the month view

### ISSUE THREAD

**Issue by simplealina** [Tuslareb/JBDatePicker#23]
Hi. I would like to prevent the user from selecting certain days in the calendar view. Is there a way for JBDatePicker to allow for the customisation of certain days of the month?

**Comment by Bubcagop** [comment]
This api can be used in example, but not in real project. Weird

**Comment by Tuslareb** [comment]
@simplealina Did you try `shouldAllowSelectionOfDay(_ date: Date?) -> Bool` ?
