### ISSUE TITLE
Week day names

### ISSUE THREAD

**Issue by CodeReaper** [Tuslareb/JBDatePicker#25]
Currently `shortWeekdaySymbols` is used as weekday labels which is fine for English with values like Mon, Tue, Wed, etc... However for at least one language that is not the right choice. `shortStandaloneWeekdaySymbols` would make more sense, the documentation even mentions these symbols as those to use in a calendar header.

I could easily make a pull request with the above change, however, the issue I am facing is that the values coming out of `shortStandaloneWeekdaySymbols` for my locale is for some reason not capitalized which they should be. Looking around I also found `veryShortStandaloneWeekdaySymbols` that for English have value like M, T, W, T, F, S, S.

I would like to solve to this issue by switching the default to `shortStandaloneWeekdaySymbols` and creating a optional string array on `JBDatePickerView` with the name of weekDaySymbols that if set is used for weekday labels.

Would you prefer a different solution or is my proposal fine?

**Comment by Tuslareb** [comment]
Wouldn't it make more sense to just declare a property in JBDatePickerViewDelegate that defaults to shortWeekdaySymbols (like it is now) and can be set to any other value of the Calendar API? This makes sure that the appearance (like capitalization) doesn't break for current users while opening the possibility to change it to another value if wanted.

**Comment by CodeReaper** [comment]
@Tuslareb - Sure the property can be on the delegate. Any other thoughts before I (later tonight
) will create a PR?

**Comment by Tuslareb** [comment]
No, I think that the delegate solution is fine. Thanks in advance for your contribution.

**Comment by Tuslareb** [comment]
Implemented in release 1.2.3.
