### ISSUE TITLE
Question: is multiple selection of dates (range) supported?

### ISSUE THREAD

**Issue by glennposadas** [Tuslareb/JBDatePicker#3]

**Comment by Tuslareb** [comment]
No, not at this moment. It's on my todo list for a future release.

**Comment by glennposadas** [comment]
Nice. Anyway, I starred the project. GJ.

**Comment by haroldogtf** [comment]
@Tuslareb range selection is already supported?

**Comment by Tuslareb** [comment]
@haroldogtf no, I'm out of coding for the moment.
