### ISSUE TITLE
Down to Swift version 2.3

### ISSUE THREAD

**Issue by ngominhtrint** [Tuslareb/JBDatePicker#4]
Hi guys,
Unlucky, I'm maintaining an old project with Swift version 2.3. Client want to have a date picker like your implementation.
So, I ask for helping. Are there any solutions to down your current source to version 2.3? Or have you implement any 2.3 version git branch.

Thank you,

**Comment by Tuslareb** [comment]
Hi, 

Unfortunately not. I started this project after the release of Swift 3, so it was developed in Swift 3 only. I don't think it's a good idea to invest much time in Swift 2.3 at this point. 

Anyway, thanks for your interest in JBDatePicker and success finding an alternative solution. 

Kind regards, 

Joost
