### ISSUE TITLE
Dates disappear 

### ISSUE THREAD

**Issue by Nathan961207** [Tuslareb/JBDatePicker#7]
Current, previous and next month dates are shown but any other months dates are not shown. When i scroll to the months where the dates are not shown then scroll back all months dates are no longer visible.

This delegate method still gets called:
 func didPresentOtherMonth(_ monthView: JBDatePickerMonthView)

**Comment by Tuslareb** [comment]
I can't replicate this issue. Can you provide more details about how you are implementing JBDatePicker?

**Comment by Nathan961207** [comment]
I am implementing JBDatePicker in a tableview cell, the cell is hidden when the tableview is loaded and upon selecting the "date" cell, the hidden cell expands revealing the JBDatePicker.

TableView is static and the controller is a UITableViewController

```
lazy var datePicker: JBDatePickerView = {
        let datepicker = JBDatePickerView()
        datepicker.delegate = self
        datepicker.isHidden = true
        return datepicker
    }()
override func viewDidLoad() {
        super.viewDidLoad()
        tableView.estimatedRowHeight = 50
        tableView.rowHeight = UITableViewAutomaticDimension
        setUpView()
    }
 override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        datePicker.updateLayout()
    }

```

**Comment by Tuslareb** [comment]
It possibly is caused by the fact that the next months don't get the correct frame. How does datePicker get it's frame anyway? Are you using autoLayout to pin it to the edges of the tableViewCell?

To debug, please go into the JBDatePicker framework and go to the class JBDatePickerView.swift. Next, go to the updateLayout() method, and after the declaration of availableRectForScrollView, add the following print statement:

`print("available rect: \(availableRectForScrollView)")`

Now, when swiping through the months, are you getting an unexpected frame when entering a month without dates?

**Comment by Nathan961207** [comment]
The datePicker gets it frame like this 

```
DatePickerCell.addSubview(datePicker)
DatePickerCell.addConstraintsWithFormat("H:|[v0]|", views: datePicker)
DatePickerCell.addConstraintsWithFormat("V:|[v0]|", views: datePicker)
```

This is the addConstraintsWithFormat() code:

```
extension UIView {
    func addConstraintsWithFormat(_ format: String, views: UIView...) {
        var viewsDictionary = [String: UIView]()
        for (index, view) in views.enumerated() {
            let key = "v\(index)"
            view.translatesAutoresizingMaskIntoConstraints = false
            viewsDictionary[key] = view
        }
        
        addConstraints(NSLayoutConstraint.constraints(withVisualFormat: format, options: NSLayoutFormatOptions(), metrics: nil, views: viewsDictionary))
        
    }
    
}
```

Upon loading the UITableViewController i get "available rect: (0.0, 0.0, 375.0, 0.0)" for the current, previous and the next month because the cell is collapsed(0 height).

When i expand the cell containing the datePicker i get the following frame "available rect: (0.0, 44.0, 375.0, 176.0)" for the current month only and on swipe it gets called once then never again.

**Comment by Tuslareb** [comment]
Thanks for the info. I was able to replicate it and I'm working on a fix. The problem is that viewDidLayoutSubviews isn't called in a UITableViewController when presenting a new month. JBDatePicker is highly dependent on this call.

**Comment by Nathan961207** [comment]
Okay thanks, i will be waiting!!

**Comment by Tuslareb** [comment]
It should be fixed with the latest release (1.1.0). This release also removes the need to implement 'viewDidLayoutSubviews' in your UITableViewController.

Please let me know if it works in your setup.

**Comment by Nathan961207** [comment]
Works excellent now! Thanks for the quick fix

**Comment by surendar574** [comment]
Can you please let me know how to show current date is maximum date in JBDatePicker?
