### ISSUE TITLE
OutDates

### ISSUE THREAD

**Issue by DiegoCaridei** [Tuslareb/JBDatePicker#8]
If i click on  the day of not current month and if i print the date the day is correct but not the month.
<img width="371" alt="cal" src="https://cloud.githubusercontent.com/assets/1045744/22330610/672b9170-e3c7-11e6-9ea8-f48dffa710c6.png">
for example if you see the screenshot, If i click on 29 it return to me 29 Dec but is 29 Nov.

**Comment by Nathan961207** [comment]
That is correct, have you tried using the value in a UILabel?

**Comment by DiegoCaridei** [comment]
Yes I tried and return to me 29 dec  and not 29 nov

**Comment by Tuslareb** [comment]
That's a major bug. I'll fix it as soon as possible. It works fine for the 'next month' dates by the way, the issue only appears on the 'previous month' dates.

**Comment by DiegoCaridei** [comment]
That's correct, the issue only appears on the 'previous month' dates.

**Comment by DiegoCaridei** [comment]
@Tuslareb  thanks

**Comment by Tuslareb** [comment]
Fixed with release 1.1.1. @DiegoCaridei Please let me know if you still have any issues.
